### ISSUE TITLE
Implement real-time tracking

### ISSUE THREAD

**Issue by Isabella-Tsui** [palodaman/crowdship#44]
**Feature**
Real time package tracking

**Description** 
Allows a driver to start a package deliver and while they are driving to the destination senders should be able to see where the driver is going. 

**Requirements**
- [ ] Drivers should be able to click a button in their active deliveries which starts their journey
- [ ] Sender should be able to go to the delivery dashboard select their package and see where it is on a map
- [ ] The start delivery button should become a complete delivery button

**Estimated Time Approximate:** 30hrs 
**Time Taken:**  0
**Status:** Incomplete

**Comment by Isabella-Tsui** [comment]
Leaving this feature for another time. After talking with our target market we have decided that this is a nice-to-have, and it should be implemented at a later date.

**Comment by Isabella-Tsui** [comment]
Upon further consideration, we are going to fake this feature. This has been implemented in https://github.com/palodaman/crowdship/issues/67.
